## Задание 1
### Этап 1. Получение данных

Сначала изучим данные, предоставленные для проекта.

Набор данных содержит подробную информацию об общем количестве проходов пассажиров на станции метрополитена через турникеты по входу и об общем количестве выходов, осуществленных пассажирами со станций метрополитена.
Источник данных: Портал открытых данных Правительства Москвы: Пассажиропоток по станциям Московского метрополитена

In [1]:
import pandas as pd
import numpy as np

Скачиваем данные, определяем разделитель, пропускаем некоторые строки для корректной загрузки и загружаем данные в датафрейм.

In [2]:
df = pd.read_csv("C:\\Users\\Mariya\\Downloads\\Пассажиропоток_МосМетро_3.csv", sep = '|',
                 skiprows=[0, 1, 2, 3, 5, 6, 1380])

Получение первых 10 строк таблицы.

In [3]:
df.head(10)

,NameOfStation,Line,Year,Quarter,IncomingPassengers,OutgoingPassengers,global_id,NameOfStation_en,Line_en,Year_en,Quarter_en,IncomingPassengers_en,OutgoingPassengers_en,Unnamed: 13
0,Митино,Арбатско-Покровская линия,2021.0,I квартал,1913498.0,1829031.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Волоколамская,Арбатско-Покровская линия,2021.0,I квартал,1236714.0,1222309.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Строгино,Арбатско-Покровская линия,2021.0,I квартал,1938816.0,1903731.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Крылатское,Арбатско-Покровская линия,2021.0,I квартал,1849616.0,1818208.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Площадь Революции,Арбатско-Покровская линия,2021.0,I квартал,2324687.0,2319343.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Бауманская,Арбатско-Покровская линия,2021.0,I квартал,3757697.0,3919091.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Первомайская,Арбатско-Покровская линия,2021.0,I квартал,2554914.0,2542396.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Беломорская,Замоскворецкая линия,2021.0,I квартал,2093304.0,2007519.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Речной вокзал,Замоскворецкая линия,2021.0,I квартал,1976604.0,1932752.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Водный стадион,Замоскворецкая линия,2021.0,I квартал,2798329.0,2787327.0,1.138976e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Общая информация о данных таблицы df

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1373 entries, 0 to 1372
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NameOfStation          1373 non-null   str
 1   Line                   1372 non-null   str
 2   Year                   1372 non-null   float64
 3   Quarter                1372 non-null   str
 4   IncomingPassengers     1372 non-null   float64
 5   OutgoingPassengers     1372 non-null   float64
 6   global_id              1372 non-null   float64
 7   NameOfStation_en       0 non-null      float64
 8   Line_en                0 non-null      float64
 9   Year_en                0 non-null      float64
 10  Quarter_en             0 non-null      float64
 11  IncomingPassengers_en  0 non-null      float64
 12  OutgoingPassengers_en  0 non-null      float64
 13  Unnamed: 13            0 non-null      float64
dtypes: float64(11), str(3)
memory usage: 150.3 KB

##  Этап 2. Решение задачи

Определяем сколько всего было входов по всем станциям за всё время (сумма по столбцу IncomingPassengers)

In [8]:
pd.set_option('display.width', None)
result = df['IncomingPassengers'].sum()
print(f'{result:.0f}')

2514195123

## Задание 2
### Этап 1. Получение данных

Сначала изучим данные, предоставленные для проекта.

Набор данных содержит подробную информацию об общем количестве проходов пассажиров на станции метрополитена через турникеты по входу и об общем количестве выходов, осуществленных пассажирами со станций метрополитена.
Источник данных: Портал открытых данных Правительства Москвы: Пассажиропоток по станциям Московского метрополитена

Скачиваем данные, определяем разделитель, конвертируем 0, NULL, None, не указано в NaN и загружаем данные в датафрейм.

In [10]:
df2 = pd.read_csv("C:\\Users\\Mariya\\Downloads\\Пассажиропоток_МосМетро_4.csv", sep = '|',
                 skiprows=[1], na_values={'IncomingPassengers' : [0, 'не указано']})
pd.set_option('display.width', None)

Получение первых 10 строк таблицы.

In [11]:
df2.head(10)

,NameOfStation,Line,Year,Quarter,IncomingPassengers,OutgoingPassengers,global_id,NameOfStation_en,Line_en,Year_en,Quarter_en,IncomingPassengers_en,OutgoingPassengers_en,Unnamed: 13
0,Митино,Арбатско-Покровская линия,2021,I квартал,1913498.0,1829031.0,1138975996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Волоколамская,Арбатско-Покровская линия,2021,I квартал,1236714.0,1222309.0,1138975997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Строгино,Арбатско-Покровская линия,2021,I квартал,1938816.0,1903731.0,1138975999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Крылатское,Арбатско-Покровская линия,2021,I квартал,1849616.0,1818208.0,1138976000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Площадь Революции,Арбатско-Покровская линия,2021,I квартал,2324687.0,2319343.0,1138976008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Бауманская,Арбатско-Покровская линия,2021,I квартал,3757697.0,3919091.0,1138976010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Первомайская,Арбатско-Покровская линия,2021,I квартал,2554914.0,2542396.0,1138976015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Беломорская,Замоскворецкая линия,2021,I квартал,2093304.0,2007519.0,1138976018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Речной вокзал,Замоскворецкая линия,2021,I квартал,1976604.0,1932752.0,1138976019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Водный стадион,Замоскворецкая линия,2021,I квартал,2798329.0,2787327.0,1138976020,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Общая информация о данных таблицы df

In [12]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NameOfStation          1372 non-null   str
 1   Line                   1372 non-null   str
 2   Year                   1372 non-null   int64
 3   Quarter                1372 non-null   str
 4   IncomingPassengers     1335 non-null   float64
 5   OutgoingPassengers     1371 non-null   float64
 6   global_id              1372 non-null   int64
 7   NameOfStation_en       0 non-null      float64
 8   Line_en                0 non-null      float64
 9   Year_en                0 non-null      float64
 10  Quarter_en             0 non-null      float64
 11  IncomingPassengers_en  0 non-null      float64
 12  OutgoingPassengers_en  0 non-null      float64
 13  Unnamed: 13            0 non-null      float64
dtypes: float64(9), int64(2), str(3)
memory usage: 150.2 KB

##  Этап 2. Решение задачи

Определяем количество записей, у которых пропущено значение в столбце 'IncomingPassengers'

In [14]:
mask = df2['IncomingPassengers'].isnull()
print(len(df2[mask]['IncomingPassengers']))

37